# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a0abb0fb0d7b4791721f63cf9850833c875617d7f5f74360ea2fe8a8b5b2193fa9629c1cda9f77cba8e845a81ebbcfc59b7d5fbaf15a949527e2387283b6d01

test:
  secret_key_base: 95082b308140e0001cabcb5fba9dc1f92e0cd21d4d30ba41ed458735245ab358e9dcb27dcbca3e855b488f6d713730711780e5710ddbab9453873c532ebad65f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
